# Generated by Django 4.2.29 on 2026-03-25 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoadCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('max_point_load', 'Max Point Load'), ('max_axle_load', 'Max Axle Load'), ('max_uniform_distributed_load', 'Max Uniform Distributed Load'), ('max_displacement_size', 'Max Displacement Size')], max_length=64)),
                ('metric', models.CharField(choices=[('kN', 'kilonewtons (kN)'), ('t', 'tonnes (t)'), ('kPa', 'kilopascal (kPa)')], max_length=16)),
                ('max_load', models.FloatField()),
                ('details', models.TextField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_capacities', to='assets.asset')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='assets.location'),
        ),
        migrations.AddConstraint(
            model_name='loadcapacity',
            constraint=models.UniqueConstraint(fields=('asset', 'name'), name='unique_capacity_name_per_asset'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('location', 'name'), name='unique_asset_per_location'),
        ),
    ]
