# Generated by Django 6.0.3 on 2026-04-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadcapacity',
            name='name',
            field=models.CharField(choices=[('max_point_load', 'Max Point Load'), ('max_axle_load', 'Max Axle Load'), ('max_uniform_distributor_load', 'Max Uniform Distributor Load'), ('max_displacement_size', 'Max Displacement Size')], max_length=64),
        ),
    ]
