# Generated by Django 6.0.3 on 2026-04-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_loadcapacity_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='drawing_file',
            field=models.FileField(blank=True, null=True, upload_to='drawings/'),
        ),
    ]
