# Generated by Django 4.2.29 on 2026-03-24 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(choices=[('crane_with_outriggers', 'Crane with outriggers'), ('mobile_crane', 'Mobile crane'), ('heavy_vehicle', 'Heavy vehicle'), ('elevated_work_platform', 'Elevated Work Platform'), ('storage_load', 'Storage Load'), ('vessel', 'Vessel')], max_length=64)),
                ('equipment_model', models.TextField(blank=True, null=True)),
                ('load_value', models.FloatField()),
                ('capacity_name', models.CharField(choices=[('max_point_load', 'Max Point Load'), ('max_axle_load', 'Max Axle Load'), ('max_uniform_distributed_load', 'Max Uniform Distributed Load'), ('max_displacement_size', 'Max Displacement Size')], max_length=64)),
                ('capacity_metric', models.CharField(choices=[('kN', 'kilonewtons (kN)'), ('t', 'tonnes (t)'), ('kPa', 'kilopascal (kPa)')], max_length=16)),
                ('capacity_limit', models.FloatField()),
                ('is_compliant', models.BooleanField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='assets.asset')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='assets.location')),
            ],
        ),
    ]
