# Generated by Django 6.0.3 on 2026-04-05 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='capacity_name',
            field=models.CharField(choices=[('max_point_load', 'Max Point Load'), ('max_axle_load', 'Max Axle Load'), ('max_uniform_distributor_load', 'Max Uniform Distributor Load'), ('max_displacement_size', 'Max Displacement Size')], max_length=64),
        ),
    ]
